---
- name: ensure apt cache is up to date
  apt: update_cache=yes
- name: ensure packages are installed
  apt: name={{item}}
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2

- name: ensure user is created
  sudo_user: postgres
  postgresql_user: name={{customer_name}} password={{db_pass}} role_attr_flags=CREATEDB

- name: ensure database is created and above user is set as owner
  sudo_user: postgres
  postgresql_db: name={{db_name}}
                 owner='{{customer_name}}'
